[IClientUser]
interface_id = 1
vtable_rva = "0x1301A60"

[IClientUser.GetSteamID]
method_index = 10
funcHash = "0xD6FC3200"
wrapper_rva = "0x790E70"
fencepost = "0xD7058CA5"
argc = 0

[IClientUser.GetAppOwnershipTicketExtendedData]
method_index = 105
funcHash = "0xC7E71245"
wrapper_rva = "0x7593C0"
fencepost = "0xC8449840"
argc = 2

[IClientUser.RequestEncryptedAppTicket]
method_index = 120
funcHash = "0x25D6BB1D"
wrapper_rva = "0x84EEE0"
fencepost = "0x2646B663"
argc = 2

[IClientUser.GetEncryptedAppTicket]
method_index = 121
funcHash = "0xE0468CB4"
wrapper_rva = "0x76C2B0"
fencepost = "0xE0B80200"
argc = 1

[IClientUtils]
interface_id = 4
vtable_rva = "0x1307498"

[IClientUtils.GetAppID]
method_index = 19
funcHash = "0x09607EC4"
wrapper_rva = "0x758120"
fencepost = "0x0AFE7552"
argc = 0

[IClientUtils.GetAPICallResult]
method_index = 24
funcHash = "0x2D3D3947"
wrapper_rva = "0x753F60"
fencepost = "0x2EDF5EE6"
argc = 3
